project_id = "ciywuwcwixbvmsezppya"

[functions.update-profile]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.reset-password-otp]
verify_jwt = false

[functions.resend-otp]
verify_jwt = false

[functions.signup]
verify_jwt = false

[functions.products]
verify_jwt = false

[functions.wishlist]
verify_jwt = false

[functions.get-profile]
verify_jwt = false
