project_id = "ciywuwcwixbvmsezppya"

[functions.update-profile]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.reset-password-otp]
verify_jwt = false

[functions.resend-otp]
verify_jwt = false

[functions.signup]
verify_jwt = false

[functions.products]
verify_jwt = false

[functions.wishlist]
verify_jwt = false

[functions.get-profile]
verify_jwt = false

[functions.orders]
verify_jwt = false

[functions.delivery-requests]
verify_jwt = false

[functions.conversations]
verify_jwt = false

[functions.notifications-all]
verify_jwt = false

[functions.notifications]
verify_jwt = false

[functions.change-password]
verify_jwt = false

[functions.logout]
verify_jwt = false

[functions.addresses]
verify_jwt = false

[functions.seller-delivery-requests]
verify_jwt = false

[functions.admin-delivery-requests]
verify_jwt = false

[functions.notification-settings]
verify_jwt = false

[functions.locations]
verify_jwt = false

[functions.upload-images]
verify_jwt = false

[functions.mamo-payment]
verify_jwt = false

[functions.mamo-webhook]
verify_jwt = false
